return {}
-- -- JDTLS configuración final: extremadamente básica pero con soporte para Lombok
-- local home = os.getenv("HOME")
-- local java_home = os.getenv("JAVA_HOME")
--
-- if not java_home or java_home == "" then
--     vim.notify("JAVA_HOME no está configurado", vim.log.levels.ERROR)
--     return {}
-- end
--
-- local java_binary = java_home .. "/bin/java"
-- local jdtls_path = home .. "/workspaces/utils/jdt-language-server-1.52.0-202510230337"
-- local lombok_jar = home .. "/workspaces/utils/lombok.jar"
-- local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
-- local workspace_dir = vim.fn.stdpath('data') .. '/jdtls-workspace/' .. project_name
-- local config_dir = jdtls_path .. "/config_mac"
--
-- -- Buscar launcher jar
-- local launcher_glob = jdtls_path .. "/plugins/org.eclipse.equinox.launcher_*.jar"
-- local launcher_jar = vim.fn.glob(launcher_glob, true)
--
-- -- Java command con opciones mínimas y soporte básico para Lombok
-- local java_cmd = {
--     java_binary,
--     -- Suprime advertencias de módulos incubator
--     "-XX:+UnlockDiagnosticVMOptions",
--     "-XX:+IgnoreUnrecognizedVMOptions",
--     "-Djdk.module.showModuleResolution=false",
--     -- Lombok
--     "-javaagent:" .. lombok_jar,
--     -- JDTLS esencial
--     "-Declipse.application=org.eclipse.jdt.ls.core.id1",
--     "-Dosgi.bundles.defaultStartLevel=4",
--     "-Declipse.product=org.eclipse.jdt.ls.core.product",
--     "-Dlog.protocol=true",
--     "-Dlog.level=ALL",
--     -- Configuración de memoria
--     "-Xms512m",
--     "-Xmx1G",
--     -- Archivo JAR, configuración y datos
--     "-jar", launcher_jar,
--     "-configuration", config_dir,
--     "-data", workspace_dir
-- }
--
-- return {
--     'mfussenegger/nvim-jdtls',
--     config = function()
--         -- Clean workspace on startup
--         local ws_dir = vim.fn.stdpath('data') .. '/jdtls-workspace/' .. project_name
--         if vim.fn.isdirectory(ws_dir) == 1 then
--             local cmd = "rm -rf " .. vim.fn.shellescape(ws_dir)
--             os.execute(cmd)
--             vim.notify("Workspace limpiado automáticamente en inicio", vim.log.levels.INFO)
--         end
--
--         vim.api.nvim_create_autocmd({"FileType"}, {
--             pattern = {"java"},
--             callback = function()
--                 -- Solo para archivos Java
--                 local filename = vim.api.nvim_buf_get_name(0)
--                 if not filename:match("%.java$") then
--                     return
--                 end
--
--                 -- Intentar iniciar JDTLS
--                 local status, jdtls = pcall(require, 'jdtls')
--                 if not status then
--                     vim.notify("No se pudo cargar jdtls", vim.log.levels.ERROR)
--                     return
--                 end
--
--                 -- Configuración ultra simple para evitar problemas
--                 local config = {
--                     cmd = java_cmd,
--                     root_dir = require('jdtls.setup').find_root({'pom.xml', 'build.gradle'}),
--                     settings = {
--                         java = {
--                             configuration = {
--                                 updateBuildConfiguration = "automatic",
--                                 runtimes = {{
--                                     name = "JavaSE-21",
--                                     path = java_home,
--                                     default = true
--                                 }},
--                             },
--                             compiler = {
--                                 lombokEnabled = true
--                             }
--                         }
--                     }
--                 }
--
--                 -- Iniciar servidor
--                 jdtls.start_or_attach(config)
--                 vim.notify("JDTLS iniciado con configuración básica", vim.log.levels.INFO)
--             end
--         })
--
--         -- Comando para verificar estado y limpiar
--         vim.api.nvim_create_user_command("JdtLimpio", function()
--             -- Detener JDTLS
--             pcall(function() vim.cmd("LspStop jdtls") end)
--             vim.notify("JDTLS detenido", vim.log.levels.INFO)
--
--             -- Eliminar workspace
--             local ws_dir = vim.fn.stdpath('data') .. '/jdtls-workspace/' .. project_name
--             if vim.fn.isdirectory(ws_dir) == 1 then
--                 local cmd = "rm -rf " .. vim.fn.shellescape(ws_dir)
--                 os.execute(cmd)
--                 vim.notify("Workspace eliminado: " .. ws_dir, vim.log.levels.INFO)
--             end
--
--             -- Limpiar logs
--             local lsp_log = vim.fn.stdpath('state') .. '/lsp.log'
--             if vim.fn.filereadable(lsp_log) == 1 then
--                 os.execute("echo '' > " .. vim.fn.shellescape(lsp_log))
--                 vim.notify("Log LSP limpiado", vim.log.levels.INFO)
--             end
--
--             vim.notify("Por favor reinicia Neovim completamente", vim.log.levels.INFO)
--         end, {})
--     end
-- }
