return {
  -- {
  --   -- Deshabilitar resaltado de fondo en Markdown
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = function(_, opts)
  --     -- Añadir configuración específica para markdown
  --     if opts.highlight then
  --       opts.highlight.disable = opts.highlight.disable or {}
  --       if type(opts.highlight.disable) == "table" then
  --         table.insert(opts.highlight.disable, "markdown")
  --       end
  --     end
  --     return opts
  --   end,
  -- },
  -- {
  --   -- Configurar highlighting básico para Markdown
  --   "neovim/nvim-lspconfig",
  --   opts = function(_, opts)
  --     if not opts.servers then opts.servers = {} end
  --     if not opts.servers.marksman then
  --       opts.servers.marksman = {
  --         filetypes = { "markdown" }
  --       }
  --     end
  --     return opts
  --   end
  -- },
  -- {
  --   -- Establece colores simples para markdown
  --   "render-markdown.nvim",
  --   enabled = false, -- Deshabilita el plugin que puede estar añadiendo colores excesivos
  -- },
  -- {
  --   --   -- Configuración de colores para Markdown
  --   --   name = "markdown-colors",
  --   --   event = { "BufRead", "BufNewFile" },
  --   --   ft = { "markdown", "md" },
  --   --   config = function()
  --   --     vim.api.nvim_create_autocmd("FileType", {
  --   --       pattern = { "markdown" },
  --   --       callback = function()
  --   --         -- Establecer colores básicos para markdown sin fondos llamativos
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", { fg = "#61afef", bold = true, bg = "NONE" })
  --   --
  --   --         vim.api.nvim_set_hl(0, "@markup.bold.markdown", { bold = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.italic.markdown", { italic = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.quote.markdown", { fg = "#98c379", bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.raw.markdown", { fg = "#e5c07b", bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.raw.block.markdown", { fg = "#e5c07b", bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.link.markdown", { fg = "#c678dd", underline = true, bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.link.label.markdown", { fg = "#56b6c2", bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.list.markdown", { fg = "#e06c75", bg = "NONE" })
  --   --
  --   --         -- Desactivar fondos de color
  --   --         vim.api.nvim_set_hl(0, "markdownCode", { bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "markdownCodeBlock", { bg = "NONE" })
  --   --         vim.api.nvim_set_hl(0, "@markup.raw.delimiter.markdown", { fg = "#abb2bf", bg = "NONE" })
  --   --       end,
  --   --     })
  --   --
  --   --     -- Usar syntax basico en lugar de treesitter para markdown
  --   --     vim.g.markdown_recommended_style = 0
  --   --     vim.g.markdown_syntax_conceal = 0
  --   --   end,
  -- },
}
