-- local home         = os.getenv("HOME")
-- local java_home    = home .. "/.asdf/installs/java/zulu-21.42.19/zulu-21.jdk/Contents/Home"
-- local java_bin     = java_home .. "/bin/java"
-- local lombok_jar   = home .. "/workspaces/utils/lombok-edge.jar"
-- local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
-- -- Root detection: prioritize multi-module aggregators (settings.gradle/.git)
--
-- local java_cmd     = {
-- 	java_bin,
-- 	"-Declipse.application=org.eclipse.jdt.ls.core.id1",
-- 	"-Dosgi.bundles.defaultStartLevel=4",
-- 	"-Declipse.product=org.eclipse.jdt.ls.core.product",
-- 	"-Dosgi.checkConfiguration=true",
-- 	"-Dosgi.sharedConfiguration.area=" .. home .. "/.local/share/nvim/mason/share/jdtls/config",
-- 	"-Dosgi.sharedConfiguration.area.readOnly=true",
-- 	"-Dosgi.configuration.cascaded=true",
-- 	"-Xms1G",
-- 	"--add-modules=ALL-SYSTEM",
-- 	"--add-opens", "java.base/java.util=ALL-UNNAMED",
-- 	"--add-opens", "java.base/java.lang=ALL-UNNAMED",
-- 	"-javaagent:" .. lombok_jar,
-- 	"-jar", home .. "/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar",
-- 	"-configuration", home .. "/.cache/nvim/jdtls/config",
-- 	"-data", home .. "/.cache/nvim/jdtls/workspaces/" .. project_name,
-- }
-- vim.notify("nvim-java cmd: " .. vim.inspect(java_cmd))
return {
-- 	"nvim-java/nvim-java",
-- 	ft = "java",
-- 	dependencies = {
-- 		"neovim/nvim-lspconfig",
-- 	},
-- 	init = function()
-- 		-- Force Java 21 environment before plugin runs
-- 		vim.env.JAVA_HOME = java_home
-- 		vim.env.PATH = java_bin:match("(.+)/bin/java") .. ":" .. vim.env.PATH
-- 	end,
-- 	config = function()
-- 		-- vim.notify("nvim-java setup called")
-- 		-- Base setup for nvim-java (Spring Boot LS disabled to avoid extra JVM)
-- 		require("java").setup({
-- 			spring_boot_tools = {
-- 				enable = false, -- set to true and add java_home if you really need Boot LS
-- 		                version = "1.59.0",
-- 			},
-- 			java_test = {
-- 				enable = true,
-- 				version = "0.40.1",
-- 			},
-- 			java_debug_adapter = {
-- 				enable = true,
-- 				version = "0.58.2",
-- 			},
-- 			jdk = {
-- 				auto_install = false,
-- 			},
-- 			java = {
-- 				configuration = {
-- 					autobuild = { enabled = false },
-- 					referencesCodeLens = { enabled = false },
-- 					implementationsCodeLens = { enabled = false },
-- 					checkstyle = { enabled = false },
-- 					signatureHelp = { enabled = true },
-- 					format = { enabled = false },
-- 					project = {
-- 						importOnFirstTime = "automatic"
-- 					},
-- 					contentProvider = { preferred = "fernflower" },
-- 					-- runtimes = {
-- 					-- 	{
-- 					-- 		name = "JavaSE-21",
-- 					-- 		path = java_home,
-- 					-- 		default = true,
-- 					-- 	}
-- 					-- }
-- 				}
-- 			},
-- 			lombok = { version = "nightly" },
-- 			root_markers = {
-- 				"settings.gradle",
-- 				"settings.gradle.kts",
-- 				".git",
-- 			},
-- 			verification = {
-- 				invalid_order = true,
-- 				duplicate_setup_calls = true,
-- 				invalid_mason_registry = true,
-- 			},
-- 			mason = {
-- 				registries = {
-- 					"github:nvim-java/mason-registry",
-- 				},
-- 			},
-- 			notifications = {
-- 				-- enable 'Configuring DAP' & 'DAP configured' messages on start up
-- 				dap = true,
-- 			},
-- 			-- log_path = "/tmp/nvim-java.log",
-- 			jvm_args = {
-- 				"-Djava.home=" .. java_home,
-- 				"-Declipse.application=org.eclipse.jdt.ls.core.id1",
-- 				"-Dosgi.bundles.defaultStartLevel=4",
-- 				"-Declipse.product=org.eclipse.jdt.ls.core.product",
-- 				"-Dlog.protocol=false",
-- 				"-Dlog.level=ERROR",
-- 				"-Xms1g",
-- 				"-Xmx2g",
-- 				"--add-modules=ALL-SYSTEM",
-- 				"--add-opens", "java.base/java.util=ALL-UNNAMED",
-- 				"--add-opens", "java.base/java.lang=ALL-UNNAMED",
-- 				"-javaagent:" .. lombok_jar,
-- 			},
-- 		})
--
-- 		-- vim.lsp.config('jdtls', {})
--
-- 		-- Let nvim-java wrap jdtls; we still define root_dir & on_attach
-- 		-- Graceful shutdown
-- 		vim.api.nvim_create_autocmd("VimLeavePre", {
-- 			callback = function()
-- 				pcall(vim.cmd, "LspStop jdtls")
-- 			end,
-- 		})
-- 	end,
}
